// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.bindings

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_bindings_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_bindings_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "bindings"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}








































































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_bindings_checksum_method_cataloghandle_can_swap_languages(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_can_translate(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_default_tts_pack_id(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_dictionary_info(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_dictionary_version(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_format_version(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_generated_at(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_has_tts_voices(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_language_rows(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_delete_dictionary(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_delete_language(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_delete_superseded_tts(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_delete_tts(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_dictionary_download(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_language_download(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_plan_tts_download(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_resolve_translation_plan(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_resolve_tts_voice_files(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_translation_size_bytes(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_tts_size_bytes(
): Short
fun uniffi_bindings_checksum_method_cataloghandle_tts_voice_picker_regions(
): Short
fun uniffi_bindings_checksum_constructor_cataloghandle_open(
): Short
fun ffi_bindings_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "bindings"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    // FFI functions
    fun uniffi_bindings_fn_clone_cataloghandle(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun uniffi_bindings_fn_free_cataloghandle(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_bindings_fn_constructor_cataloghandle_open(`bundledJson`: RustBuffer.ByValue,`diskJson`: RustBuffer.ByValue,`baseDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun uniffi_bindings_fn_method_cataloghandle_can_swap_languages(`ptr`: Pointer,`fromCode`: RustBuffer.ByValue,`toCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_bindings_fn_method_cataloghandle_can_translate(`ptr`: Pointer,`fromCode`: RustBuffer.ByValue,`toCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_bindings_fn_method_cataloghandle_default_tts_pack_id(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_dictionary_info(`ptr`: Pointer,`dictionaryCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_dictionary_version(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_bindings_fn_method_cataloghandle_format_version(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_bindings_fn_method_cataloghandle_generated_at(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun uniffi_bindings_fn_method_cataloghandle_has_tts_voices(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_bindings_fn_method_cataloghandle_language_rows(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_delete_dictionary(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_delete_language(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_delete_superseded_tts(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,`selectedPackId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_delete_tts(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_dictionary_download(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_language_download(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_plan_tts_download(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,`selectedPackId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_resolve_translation_plan(`ptr`: Pointer,`fromCode`: RustBuffer.ByValue,`toCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_resolve_tts_voice_files(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_bindings_fn_method_cataloghandle_translation_size_bytes(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun uniffi_bindings_fn_method_cataloghandle_tts_size_bytes(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun uniffi_bindings_fn_method_cataloghandle_tts_voice_picker_regions(`ptr`: Pointer,`languageCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_bindings_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_bindings_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_bindings_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_bindings_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_bindings_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_bindings_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_bindings_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_bindings_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_bindings_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_bindings_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_bindings_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_bindings_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_bindings_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_bindings_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_bindings_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_bindings_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_bindings_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_bindings_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_bindings_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_bindings_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_bindings_checksum_method_cataloghandle_can_swap_languages() != 51048.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_can_translate() != 60654.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_default_tts_pack_id() != 12955.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_dictionary_info() != 40045.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_dictionary_version() != 28592.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_format_version() != 35538.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_generated_at() != 11555.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_has_tts_voices() != 62763.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_language_rows() != 43539.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_delete_dictionary() != 62985.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_delete_language() != 58057.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_delete_superseded_tts() != 58671.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_delete_tts() != 59174.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_dictionary_download() != 63219.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_language_download() != 41508.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_plan_tts_download() != 59319.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_resolve_translation_plan() != 15274.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_resolve_tts_voice_files() != 40314.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_translation_size_bytes() != 52553.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_tts_size_bytes() != 14893.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_method_cataloghandle_tts_voice_picker_regions() != 20449.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bindings_checksum_constructor_cataloghandle_open() != 5436.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


public interface CatalogHandleInterface {
    
    fun `canSwapLanguages`(`fromCode`: kotlin.String, `toCode`: kotlin.String): kotlin.Boolean
    
    fun `canTranslate`(`fromCode`: kotlin.String, `toCode`: kotlin.String): kotlin.Boolean
    
    fun `defaultTtsPackId`(`languageCode`: kotlin.String): kotlin.String?
    
    fun `dictionaryInfo`(`dictionaryCode`: kotlin.String): DictionaryInfo?
    
    fun `dictionaryVersion`(): kotlin.Int
    
    fun `formatVersion`(): kotlin.Int
    
    fun `generatedAt`(): kotlin.Long
    
    fun `hasTtsVoices`(`languageCode`: kotlin.String): kotlin.Boolean
    
    fun `languageRows`(): List<LanguageRow>
    
    fun `planDeleteDictionary`(`languageCode`: kotlin.String): DeletePlan
    
    fun `planDeleteLanguage`(`languageCode`: kotlin.String): DeletePlan
    
    fun `planDeleteSupersededTts`(`languageCode`: kotlin.String, `selectedPackId`: kotlin.String): DeletePlan
    
    fun `planDeleteTts`(`languageCode`: kotlin.String): DeletePlan
    
    fun `planDictionaryDownload`(`languageCode`: kotlin.String): DownloadPlan?
    
    fun `planLanguageDownload`(`languageCode`: kotlin.String): DownloadPlan
    
    fun `planTtsDownload`(`languageCode`: kotlin.String, `selectedPackId`: kotlin.String?): DownloadPlan?
    
    fun `resolveTranslationPlan`(`fromCode`: kotlin.String, `toCode`: kotlin.String): TranslationPlan?
    
    fun `resolveTtsVoiceFiles`(`languageCode`: kotlin.String): TtsVoiceFiles?
    
    fun `translationSizeBytes`(`languageCode`: kotlin.String): kotlin.Long
    
    fun `ttsSizeBytes`(`languageCode`: kotlin.String): kotlin.Long
    
    fun `ttsVoicePickerRegions`(`languageCode`: kotlin.String): List<TtsVoicePickerRegion>
    
    companion object
}

open class CatalogHandle: Disposable, AutoCloseable, CatalogHandleInterface
{

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_bindings_fn_free_cataloghandle(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_bindings_fn_clone_cataloghandle(pointer!!, status)
        }
    }

    override fun `canSwapLanguages`(`fromCode`: kotlin.String, `toCode`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_can_swap_languages(
        it, FfiConverterString.lower(`fromCode`),FfiConverterString.lower(`toCode`),_status)
}
    }
    )
    }
    

    override fun `canTranslate`(`fromCode`: kotlin.String, `toCode`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_can_translate(
        it, FfiConverterString.lower(`fromCode`),FfiConverterString.lower(`toCode`),_status)
}
    }
    )
    }
    

    override fun `defaultTtsPackId`(`languageCode`: kotlin.String): kotlin.String? {
            return FfiConverterOptionalString.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_default_tts_pack_id(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `dictionaryInfo`(`dictionaryCode`: kotlin.String): DictionaryInfo? {
            return FfiConverterOptionalTypeDictionaryInfo.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_dictionary_info(
        it, FfiConverterString.lower(`dictionaryCode`),_status)
}
    }
    )
    }
    

    override fun `dictionaryVersion`(): kotlin.Int {
            return FfiConverterInt.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_dictionary_version(
        it, _status)
}
    }
    )
    }
    

    override fun `formatVersion`(): kotlin.Int {
            return FfiConverterInt.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_format_version(
        it, _status)
}
    }
    )
    }
    

    override fun `generatedAt`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_generated_at(
        it, _status)
}
    }
    )
    }
    

    override fun `hasTtsVoices`(`languageCode`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_has_tts_voices(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `languageRows`(): List<LanguageRow> {
            return FfiConverterSequenceTypeLanguageRow.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_language_rows(
        it, _status)
}
    }
    )
    }
    

    override fun `planDeleteDictionary`(`languageCode`: kotlin.String): DeletePlan {
            return FfiConverterTypeDeletePlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_delete_dictionary(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `planDeleteLanguage`(`languageCode`: kotlin.String): DeletePlan {
            return FfiConverterTypeDeletePlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_delete_language(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `planDeleteSupersededTts`(`languageCode`: kotlin.String, `selectedPackId`: kotlin.String): DeletePlan {
            return FfiConverterTypeDeletePlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_delete_superseded_tts(
        it, FfiConverterString.lower(`languageCode`),FfiConverterString.lower(`selectedPackId`),_status)
}
    }
    )
    }
    

    override fun `planDeleteTts`(`languageCode`: kotlin.String): DeletePlan {
            return FfiConverterTypeDeletePlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_delete_tts(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `planDictionaryDownload`(`languageCode`: kotlin.String): DownloadPlan? {
            return FfiConverterOptionalTypeDownloadPlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_dictionary_download(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `planLanguageDownload`(`languageCode`: kotlin.String): DownloadPlan {
            return FfiConverterTypeDownloadPlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_language_download(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `planTtsDownload`(`languageCode`: kotlin.String, `selectedPackId`: kotlin.String?): DownloadPlan? {
            return FfiConverterOptionalTypeDownloadPlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_plan_tts_download(
        it, FfiConverterString.lower(`languageCode`),FfiConverterOptionalString.lower(`selectedPackId`),_status)
}
    }
    )
    }
    

    override fun `resolveTranslationPlan`(`fromCode`: kotlin.String, `toCode`: kotlin.String): TranslationPlan? {
            return FfiConverterOptionalTypeTranslationPlan.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_resolve_translation_plan(
        it, FfiConverterString.lower(`fromCode`),FfiConverterString.lower(`toCode`),_status)
}
    }
    )
    }
    

    override fun `resolveTtsVoiceFiles`(`languageCode`: kotlin.String): TtsVoiceFiles? {
            return FfiConverterOptionalTypeTtsVoiceFiles.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_resolve_tts_voice_files(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `translationSizeBytes`(`languageCode`: kotlin.String): kotlin.Long {
            return FfiConverterLong.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_translation_size_bytes(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `ttsSizeBytes`(`languageCode`: kotlin.String): kotlin.Long {
            return FfiConverterLong.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_tts_size_bytes(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    override fun `ttsVoicePickerRegions`(`languageCode`: kotlin.String): List<TtsVoicePickerRegion> {
            return FfiConverterSequenceTypeTtsVoicePickerRegion.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_method_cataloghandle_tts_voice_picker_regions(
        it, FfiConverterString.lower(`languageCode`),_status)
}
    }
    )
    }
    

    

    
    companion object {
        
    @Throws(CatalogOpenException::class) fun `open`(`bundledJson`: kotlin.String, `diskJson`: kotlin.String?, `baseDir`: kotlin.String): CatalogHandle {
            return FfiConverterTypeCatalogHandle.lift(
    uniffiRustCallWithError(CatalogOpenException) { _status ->
    UniffiLib.INSTANCE.uniffi_bindings_fn_constructor_cataloghandle_open(
        FfiConverterString.lower(`bundledJson`),FfiConverterOptionalString.lower(`diskJson`),FfiConverterString.lower(`baseDir`),_status)
}
    )
    }
    

        
    }
    
}

/**
 * @suppress
 */
public object FfiConverterTypeCatalogHandle: FfiConverter<CatalogHandle, Pointer> {

    override fun lower(value: CatalogHandle): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): CatalogHandle {
        return CatalogHandle(value)
    }

    override fun read(buf: ByteBuffer): CatalogHandle {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: CatalogHandle) = 8UL

    override fun write(value: CatalogHandle, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



data class DeletePlan (
    var `filePaths`: List<kotlin.String>, 
    var `directoryPaths`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDeletePlan: FfiConverterRustBuffer<DeletePlan> {
    override fun read(buf: ByteBuffer): DeletePlan {
        return DeletePlan(
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: DeletePlan) = (
            FfiConverterSequenceString.allocationSize(value.`filePaths`) +
            FfiConverterSequenceString.allocationSize(value.`directoryPaths`)
    )

    override fun write(value: DeletePlan, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`filePaths`, buf)
            FfiConverterSequenceString.write(value.`directoryPaths`, buf)
    }
}



data class DictionaryInfo (
    var `date`: kotlin.Long, 
    var `filename`: kotlin.String, 
    var `size`: kotlin.Long, 
    var `typeName`: kotlin.String, 
    var `wordCount`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDictionaryInfo: FfiConverterRustBuffer<DictionaryInfo> {
    override fun read(buf: ByteBuffer): DictionaryInfo {
        return DictionaryInfo(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: DictionaryInfo) = (
            FfiConverterLong.allocationSize(value.`date`) +
            FfiConverterString.allocationSize(value.`filename`) +
            FfiConverterLong.allocationSize(value.`size`) +
            FfiConverterString.allocationSize(value.`typeName`) +
            FfiConverterLong.allocationSize(value.`wordCount`)
    )

    override fun write(value: DictionaryInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`date`, buf)
            FfiConverterString.write(value.`filename`, buf)
            FfiConverterLong.write(value.`size`, buf)
            FfiConverterString.write(value.`typeName`, buf)
            FfiConverterLong.write(value.`wordCount`, buf)
    }
}



data class DownloadPlan (
    var `totalSize`: kotlin.Long, 
    var `tasks`: List<DownloadTask>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDownloadPlan: FfiConverterRustBuffer<DownloadPlan> {
    override fun read(buf: ByteBuffer): DownloadPlan {
        return DownloadPlan(
            FfiConverterLong.read(buf),
            FfiConverterSequenceTypeDownloadTask.read(buf),
        )
    }

    override fun allocationSize(value: DownloadPlan) = (
            FfiConverterLong.allocationSize(value.`totalSize`) +
            FfiConverterSequenceTypeDownloadTask.allocationSize(value.`tasks`)
    )

    override fun write(value: DownloadPlan, buf: ByteBuffer) {
            FfiConverterLong.write(value.`totalSize`, buf)
            FfiConverterSequenceTypeDownloadTask.write(value.`tasks`, buf)
    }
}



data class DownloadTask (
    var `packId`: kotlin.String, 
    var `installPath`: kotlin.String, 
    var `url`: kotlin.String, 
    var `sizeBytes`: kotlin.Long, 
    var `decompress`: kotlin.Boolean, 
    var `archiveFormat`: kotlin.String?, 
    var `extractTo`: kotlin.String?, 
    var `deleteAfterExtract`: kotlin.Boolean, 
    var `installMarkerPath`: kotlin.String?, 
    var `installMarkerVersion`: kotlin.Int?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDownloadTask: FfiConverterRustBuffer<DownloadTask> {
    override fun read(buf: ByteBuffer): DownloadTask {
        return DownloadTask(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalInt.read(buf),
        )
    }

    override fun allocationSize(value: DownloadTask) = (
            FfiConverterString.allocationSize(value.`packId`) +
            FfiConverterString.allocationSize(value.`installPath`) +
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterLong.allocationSize(value.`sizeBytes`) +
            FfiConverterBoolean.allocationSize(value.`decompress`) +
            FfiConverterOptionalString.allocationSize(value.`archiveFormat`) +
            FfiConverterOptionalString.allocationSize(value.`extractTo`) +
            FfiConverterBoolean.allocationSize(value.`deleteAfterExtract`) +
            FfiConverterOptionalString.allocationSize(value.`installMarkerPath`) +
            FfiConverterOptionalInt.allocationSize(value.`installMarkerVersion`)
    )

    override fun write(value: DownloadTask, buf: ByteBuffer) {
            FfiConverterString.write(value.`packId`, buf)
            FfiConverterString.write(value.`installPath`, buf)
            FfiConverterString.write(value.`url`, buf)
            FfiConverterLong.write(value.`sizeBytes`, buf)
            FfiConverterBoolean.write(value.`decompress`, buf)
            FfiConverterOptionalString.write(value.`archiveFormat`, buf)
            FfiConverterOptionalString.write(value.`extractTo`, buf)
            FfiConverterBoolean.write(value.`deleteAfterExtract`, buf)
            FfiConverterOptionalString.write(value.`installMarkerPath`, buf)
            FfiConverterOptionalInt.write(value.`installMarkerVersion`, buf)
    }
}



data class LangAvailability (
    var `hasFromEnglish`: kotlin.Boolean, 
    var `hasToEnglish`: kotlin.Boolean, 
    var `ocrFiles`: kotlin.Boolean, 
    var `dictionaryFiles`: kotlin.Boolean, 
    var `ttsFiles`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLangAvailability: FfiConverterRustBuffer<LangAvailability> {
    override fun read(buf: ByteBuffer): LangAvailability {
        return LangAvailability(
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: LangAvailability) = (
            FfiConverterBoolean.allocationSize(value.`hasFromEnglish`) +
            FfiConverterBoolean.allocationSize(value.`hasToEnglish`) +
            FfiConverterBoolean.allocationSize(value.`ocrFiles`) +
            FfiConverterBoolean.allocationSize(value.`dictionaryFiles`) +
            FfiConverterBoolean.allocationSize(value.`ttsFiles`)
    )

    override fun write(value: LangAvailability, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`hasFromEnglish`, buf)
            FfiConverterBoolean.write(value.`hasToEnglish`, buf)
            FfiConverterBoolean.write(value.`ocrFiles`, buf)
            FfiConverterBoolean.write(value.`dictionaryFiles`, buf)
            FfiConverterBoolean.write(value.`ttsFiles`, buf)
    }
}



data class LanguageInfo (
    var `code`: kotlin.String, 
    var `displayName`: kotlin.String, 
    var `shortDisplayName`: kotlin.String, 
    var `tessName`: kotlin.String, 
    var `script`: kotlin.String, 
    var `dictionaryCode`: kotlin.String, 
    var `tessdataSizeBytes`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLanguageInfo: FfiConverterRustBuffer<LanguageInfo> {
    override fun read(buf: ByteBuffer): LanguageInfo {
        return LanguageInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: LanguageInfo) = (
            FfiConverterString.allocationSize(value.`code`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterString.allocationSize(value.`shortDisplayName`) +
            FfiConverterString.allocationSize(value.`tessName`) +
            FfiConverterString.allocationSize(value.`script`) +
            FfiConverterString.allocationSize(value.`dictionaryCode`) +
            FfiConverterLong.allocationSize(value.`tessdataSizeBytes`)
    )

    override fun write(value: LanguageInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`code`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterString.write(value.`shortDisplayName`, buf)
            FfiConverterString.write(value.`tessName`, buf)
            FfiConverterString.write(value.`script`, buf)
            FfiConverterString.write(value.`dictionaryCode`, buf)
            FfiConverterLong.write(value.`tessdataSizeBytes`, buf)
    }
}



data class LanguageRow (
    var `language`: LanguageInfo, 
    var `availability`: LangAvailability
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLanguageRow: FfiConverterRustBuffer<LanguageRow> {
    override fun read(buf: ByteBuffer): LanguageRow {
        return LanguageRow(
            FfiConverterTypeLanguageInfo.read(buf),
            FfiConverterTypeLangAvailability.read(buf),
        )
    }

    override fun allocationSize(value: LanguageRow) = (
            FfiConverterTypeLanguageInfo.allocationSize(value.`language`) +
            FfiConverterTypeLangAvailability.allocationSize(value.`availability`)
    )

    override fun write(value: LanguageRow, buf: ByteBuffer) {
            FfiConverterTypeLanguageInfo.write(value.`language`, buf)
            FfiConverterTypeLangAvailability.write(value.`availability`, buf)
    }
}



data class TranslationPlan (
    var `steps`: List<TranslationStep>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTranslationPlan: FfiConverterRustBuffer<TranslationPlan> {
    override fun read(buf: ByteBuffer): TranslationPlan {
        return TranslationPlan(
            FfiConverterSequenceTypeTranslationStep.read(buf),
        )
    }

    override fun allocationSize(value: TranslationPlan) = (
            FfiConverterSequenceTypeTranslationStep.allocationSize(value.`steps`)
    )

    override fun write(value: TranslationPlan, buf: ByteBuffer) {
            FfiConverterSequenceTypeTranslationStep.write(value.`steps`, buf)
    }
}



data class TranslationStep (
    var `fromCode`: kotlin.String, 
    var `toCode`: kotlin.String, 
    var `cacheKey`: kotlin.String, 
    var `config`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTranslationStep: FfiConverterRustBuffer<TranslationStep> {
    override fun read(buf: ByteBuffer): TranslationStep {
        return TranslationStep(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: TranslationStep) = (
            FfiConverterString.allocationSize(value.`fromCode`) +
            FfiConverterString.allocationSize(value.`toCode`) +
            FfiConverterString.allocationSize(value.`cacheKey`) +
            FfiConverterString.allocationSize(value.`config`)
    )

    override fun write(value: TranslationStep, buf: ByteBuffer) {
            FfiConverterString.write(value.`fromCode`, buf)
            FfiConverterString.write(value.`toCode`, buf)
            FfiConverterString.write(value.`cacheKey`, buf)
            FfiConverterString.write(value.`config`, buf)
    }
}



data class TtsVoiceFiles (
    var `engine`: kotlin.String, 
    var `modelPath`: kotlin.String, 
    var `auxPath`: kotlin.String, 
    var `languageCode`: kotlin.String, 
    var `speakerId`: kotlin.Int?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTtsVoiceFiles: FfiConverterRustBuffer<TtsVoiceFiles> {
    override fun read(buf: ByteBuffer): TtsVoiceFiles {
        return TtsVoiceFiles(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalInt.read(buf),
        )
    }

    override fun allocationSize(value: TtsVoiceFiles) = (
            FfiConverterString.allocationSize(value.`engine`) +
            FfiConverterString.allocationSize(value.`modelPath`) +
            FfiConverterString.allocationSize(value.`auxPath`) +
            FfiConverterString.allocationSize(value.`languageCode`) +
            FfiConverterOptionalInt.allocationSize(value.`speakerId`)
    )

    override fun write(value: TtsVoiceFiles, buf: ByteBuffer) {
            FfiConverterString.write(value.`engine`, buf)
            FfiConverterString.write(value.`modelPath`, buf)
            FfiConverterString.write(value.`auxPath`, buf)
            FfiConverterString.write(value.`languageCode`, buf)
            FfiConverterOptionalInt.write(value.`speakerId`, buf)
    }
}



data class TtsVoicePackInfo (
    var `packId`: kotlin.String, 
    var `displayName`: kotlin.String, 
    var `quality`: kotlin.String?, 
    var `sizeBytes`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTtsVoicePackInfo: FfiConverterRustBuffer<TtsVoicePackInfo> {
    override fun read(buf: ByteBuffer): TtsVoicePackInfo {
        return TtsVoicePackInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: TtsVoicePackInfo) = (
            FfiConverterString.allocationSize(value.`packId`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterOptionalString.allocationSize(value.`quality`) +
            FfiConverterLong.allocationSize(value.`sizeBytes`)
    )

    override fun write(value: TtsVoicePackInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`packId`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterOptionalString.write(value.`quality`, buf)
            FfiConverterLong.write(value.`sizeBytes`, buf)
    }
}



data class TtsVoicePickerRegion (
    var `code`: kotlin.String, 
    var `displayName`: kotlin.String, 
    var `voices`: List<TtsVoicePackInfo>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTtsVoicePickerRegion: FfiConverterRustBuffer<TtsVoicePickerRegion> {
    override fun read(buf: ByteBuffer): TtsVoicePickerRegion {
        return TtsVoicePickerRegion(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeTtsVoicePackInfo.read(buf),
        )
    }

    override fun allocationSize(value: TtsVoicePickerRegion) = (
            FfiConverterString.allocationSize(value.`code`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterSequenceTypeTtsVoicePackInfo.allocationSize(value.`voices`)
    )

    override fun write(value: TtsVoicePickerRegion, buf: ByteBuffer) {
            FfiConverterString.write(value.`code`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterSequenceTypeTtsVoicePackInfo.write(value.`voices`, buf)
    }
}





sealed class CatalogOpenException: kotlin.Exception() {
    
    class ParseFailed(
        ) : CatalogOpenException() {
        override val message
            get() = ""
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CatalogOpenException> {
        override fun lift(error_buf: RustBuffer.ByValue): CatalogOpenException = FfiConverterTypeCatalogOpenError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCatalogOpenError : FfiConverterRustBuffer<CatalogOpenException> {
    override fun read(buf: ByteBuffer): CatalogOpenException {
        

        return when(buf.getInt()) {
            1 -> CatalogOpenException.ParseFailed()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CatalogOpenException): ULong {
        return when(value) {
            is CatalogOpenException.ParseFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: CatalogOpenException, buf: ByteBuffer) {
        when(value) {
            is CatalogOpenException.ParseFailed -> {
                buf.putInt(1)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalInt: FfiConverterRustBuffer<kotlin.Int?> {
    override fun read(buf: ByteBuffer): kotlin.Int? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterInt.read(buf)
    }

    override fun allocationSize(value: kotlin.Int?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Int?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeDictionaryInfo: FfiConverterRustBuffer<DictionaryInfo?> {
    override fun read(buf: ByteBuffer): DictionaryInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeDictionaryInfo.read(buf)
    }

    override fun allocationSize(value: DictionaryInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeDictionaryInfo.allocationSize(value)
        }
    }

    override fun write(value: DictionaryInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeDictionaryInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeDownloadPlan: FfiConverterRustBuffer<DownloadPlan?> {
    override fun read(buf: ByteBuffer): DownloadPlan? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeDownloadPlan.read(buf)
    }

    override fun allocationSize(value: DownloadPlan?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeDownloadPlan.allocationSize(value)
        }
    }

    override fun write(value: DownloadPlan?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeDownloadPlan.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeTranslationPlan: FfiConverterRustBuffer<TranslationPlan?> {
    override fun read(buf: ByteBuffer): TranslationPlan? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeTranslationPlan.read(buf)
    }

    override fun allocationSize(value: TranslationPlan?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeTranslationPlan.allocationSize(value)
        }
    }

    override fun write(value: TranslationPlan?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeTranslationPlan.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeTtsVoiceFiles: FfiConverterRustBuffer<TtsVoiceFiles?> {
    override fun read(buf: ByteBuffer): TtsVoiceFiles? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeTtsVoiceFiles.read(buf)
    }

    override fun allocationSize(value: TtsVoiceFiles?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeTtsVoiceFiles.allocationSize(value)
        }
    }

    override fun write(value: TtsVoiceFiles?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeTtsVoiceFiles.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeDownloadTask: FfiConverterRustBuffer<List<DownloadTask>> {
    override fun read(buf: ByteBuffer): List<DownloadTask> {
        val len = buf.getInt()
        return List<DownloadTask>(len) {
            FfiConverterTypeDownloadTask.read(buf)
        }
    }

    override fun allocationSize(value: List<DownloadTask>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeDownloadTask.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<DownloadTask>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeDownloadTask.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeLanguageRow: FfiConverterRustBuffer<List<LanguageRow>> {
    override fun read(buf: ByteBuffer): List<LanguageRow> {
        val len = buf.getInt()
        return List<LanguageRow>(len) {
            FfiConverterTypeLanguageRow.read(buf)
        }
    }

    override fun allocationSize(value: List<LanguageRow>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeLanguageRow.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<LanguageRow>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeLanguageRow.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTranslationStep: FfiConverterRustBuffer<List<TranslationStep>> {
    override fun read(buf: ByteBuffer): List<TranslationStep> {
        val len = buf.getInt()
        return List<TranslationStep>(len) {
            FfiConverterTypeTranslationStep.read(buf)
        }
    }

    override fun allocationSize(value: List<TranslationStep>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTranslationStep.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TranslationStep>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTranslationStep.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTtsVoicePackInfo: FfiConverterRustBuffer<List<TtsVoicePackInfo>> {
    override fun read(buf: ByteBuffer): List<TtsVoicePackInfo> {
        val len = buf.getInt()
        return List<TtsVoicePackInfo>(len) {
            FfiConverterTypeTtsVoicePackInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<TtsVoicePackInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTtsVoicePackInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TtsVoicePackInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTtsVoicePackInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTtsVoicePickerRegion: FfiConverterRustBuffer<List<TtsVoicePickerRegion>> {
    override fun read(buf: ByteBuffer): List<TtsVoicePickerRegion> {
        val len = buf.getInt()
        return List<TtsVoicePickerRegion>(len) {
            FfiConverterTypeTtsVoicePickerRegion.read(buf)
        }
    }

    override fun allocationSize(value: List<TtsVoicePickerRegion>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTtsVoicePickerRegion.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TtsVoicePickerRegion>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTtsVoicePickerRegion.write(it, buf)
        }
    }
}

